// Individually reviewed lessons only. Generated by support/build-reviewed-content.mjs.
export const reviewedContent = {
  "0": {
    "paragraphs": [
      "Astronomers following asteroid activity in space estimate there is a very small chance an object large enough to [1] could strike Earth in 2032. But space agency officials say even if such an asteroid keeps heading on a path toward Earth, the world is now [2] to defend itself against such a threat. The American space agency NASA recently estimated there was a [3] chance that asteroid 2024 YR4 would hit Earth on [4]. That is the highest probability predicted for such a large space rock in modern times. Richard Moissl is head of the European Space Agency's, or ESA, [5]. While recognizing the risk the asteroid could present, he told the French news agency AFP people should not [6].",
      "Astronomers have noted that the more data they gather, the odds of a direct asteroid hit are expected to [7]. However, scientists say at a certain point the odds will likely [8]. Moissl said he thinks it is important to remember that even [9] the probability keeps rising to 100 percent, the world is \"not defenseless.\" Here are some methods currently being considered as [10] to keep humanity safe in case there is a real threat. Only one [11] has been tried against an asteroid. In 2022, NASA's Double Asteroid Redirection Test, or DART, sent a spacecraft into the 160-meter-wide Dimorphos asteroid. The effort [12] around a larger space rock. Bruce Betts is chief scientist for the nonprofit Planetary Society.",
      "He told AFP that space agencies could hit the 2024 YR4 asteroid with several spacecrafts, [13]. The asteroid discovered in December is estimated to be [14] -- about half the size of Dimorphos. \"You have to [15],\" Moissl warned. He said this is because if a spacecraft [16], it could send smaller pieces of the space rock heading toward Earth. A separate idea would involve sending a large spacecraft to fly [17]. The spacecraft would not touch the asteroid, but would use its [18] to pull it away from Earth. Moissl said another non-contact plan would put a spacecraft near the asteroid to eject [19] to push the asteroid off course.",
      "Scientists have also considered painting one side of the asteroid white. They believe this could increase the light the object reflects to make it [20]. One idea is to use a nuclear weapon against a threatening asteroid. In laboratory tests, researchers found that X-rays from [21] could move a rock. But this is considered more of a plan for kilometers-wide asteroids like the one that killed off the dinosaurs. And this method also carries the risk that a nuclear explosion could send additional pieces of the asteroid falling toward Earth. A similar method – but one considered less dangerous – would involve [22] from a spacecraft to destroy the side of an asteroid in an effort to push it away from Earth.",
      "Moissl said that [23], at least the world will have a good idea where a threatening asteroid would strike. Since astronomers believe most asteroids would at most threaten to destroy one city, efforts could be organized to get people out of an area before a strike. \"[24] is a long time to prepare,\" Moissl added. He also noted that even with the rising odds involving 2024 YR4, there is still about [25] the asteroid will miss Earth. I’m Jill Robbins."
    ],
    "answers": [
      "destroy a whole city",
      "much better-equipped",
      "3.1 percent",
      "December 22, 2032",
      "planetary defense office",
      "panic over such predictions",
      "keep rising over time",
      "drop down to zero",
      "in the unlikely event",
      "defensive measures",
      "planetary defense method",
      "successfully changed the asteroid’s orbit",
      "observing how each one changed the path",
      "40-90 meters wide",
      "take care not to overdo it",
      "only partially destroys an asteroid",
      "alongside a threatening asteroid",
      "gravitational force",
      "a continuous flow of atoms",
      "slowly change course",
      "a nuclear blast",
      "shooting laser beams",
      "if all else fails",
      "Seven-and-a-half years",
      "a 97 percent chance"
    ],
    "acceptedVariants": [
      [],
      [
        "much better equipped"
      ],
      [
        "3.1 per cent",
        "3.1%",
        "three point one percent",
        "three point one per cent"
      ],
      [
        "December 22nd 2032",
        "December twenty-second twenty thirty-two",
        "December twenty second twenty thirty two"
      ],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [
        "40 to 90 meters wide",
        "forty to ninety meters wide",
        "40-90 metres wide",
        "40 to 90 metres wide",
        "forty to ninety metres wide"
      ],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [
        "seven and a half years",
        "7.5 years",
        "7 and a half years"
      ],
      [
        "a 97 per cent chance",
        "a 97% chance",
        "a ninety-seven percent chance",
        "a ninety seven per cent chance"
      ]
    ],
    "contentRevision": "65cb0d57dc8a",
    "paraphrases": [
      [
        "defend itself against such a threat",
        "protect itself from this kind of danger",
        "Defend against và protect from diễn đạt cùng ý bảo vệ trước nguy cơ.",
        25,
        32
      ],
      [
        "panic over such predictions",
        "become extremely frightened by these forecasts",
        "Panic là hoảng sợ; predictions là những dự báo.",
        66,
        77.7
      ],
      [
        "the odds will likely drop down to zero",
        "the probability will probably fall to nothing",
        "Giữ nguyên mức độ chưa chắc chắn của likely và ý xác suất về 0.",
        87.6,
        95.5
      ],
      [
        "in the unlikely event",
        "if something improbable happens",
        "Diễn giải cụm điều kiện nói về tình huống ít có khả năng xảy ra.",
        95.5,
        108.4
      ],
      [
        "to keep humanity safe",
        "to protect the human population",
        "Humanity chỉ toàn thể con người; giữ nguyên mục đích bảo vệ.",
        108.4,
        118.4
      ],
      [
        "take care not to overdo it",
        "be careful not to go too far",
        "Overdo it là làm quá mức cần thiết.",
        170.5,
        175.3
      ],
      [
        "its gravitational force",
        "the pull created by its gravity",
        "Diễn giải lực hút hấp dẫn, không đổi thành va chạm trực tiếp.",
        194,
        202.7
      ],
      [
        "push the asteroid off course",
        "force the space rock away from its path",
        "Off course nghĩa là lệch khỏi đường đi ban đầu.",
        202.8,
        215.8
      ],
      [
        "if all else fails",
        "if none of the other methods works",
        "Giữ đúng điều kiện: các phương án còn lại đều thất bại.",
        274,
        282.7
      ],
      [
        "get people out of an area before a strike",
        "evacuate residents before an impact",
        "Evacuate diễn đạt việc đưa người ra khỏi vùng nguy hiểm trước va chạm.",
        282.7,
        294.8
      ]
    ],
    "vocabulary": [
      {
        "term": "asteroid",
        "meaning": "tiểu hành tinh",
        "note": "A small rocky object orbiting the sun."
      },
      {
        "term": "probability",
        "meaning": "xác suất; khả năng xảy ra",
        "note": "How likely an event is to happen."
      },
      {
        "term": "planetary defense",
        "meaning": "phòng vệ hành tinh",
        "note": "Measures to protect a planet from threats such as asteroid impacts."
      },
      {
        "term": "defensive measures",
        "meaning": "các biện pháp phòng vệ",
        "note": "Actions taken to protect against danger."
      },
      {
        "term": "orbit",
        "meaning": "quỹ đạo",
        "note": "The path one object follows around another in space."
      },
      {
        "term": "nonprofit",
        "meaning": "phi lợi nhuận",
        "note": "Not established to make money for owners."
      },
      {
        "term": "gravitational force",
        "meaning": "lực hấp dẫn",
        "note": "The force of attraction caused by gravity."
      },
      {
        "term": "eject",
        "meaning": "phóng; đẩy ra",
        "note": "To force something out."
      },
      {
        "term": "reflect",
        "meaning": "phản xạ",
        "note": "To send light back from a surface."
      },
      {
        "term": "off course",
        "meaning": "lệch hướng; lệch quỹ đạo",
        "note": "Away from the intended path."
      }
    ],
    "signals": [
      "However, scientists say…",
      "A separate idea would involve…",
      "A similar method…",
      "if all else fails…"
    ]
  },
  "1": {
    "paragraphs": [
      "A total lunar eclipse is about to make the moon appear [1] across the Western Hemisphere. The event will happen [2]. The best places to see the eclipse will be in North America and South America. Parts of Africa and Europe may also [3]. A lunar eclipse happens when the sun, Earth, and moon [4], with Earth [5]. This causes the Earth to [6] on the moon. In a total lunar eclipse, the Earth’s shadow covers all of the moon.",
      "Another kind of eclipse is a solar eclipse. In a solar eclipse, the moon gets in a position where it [7], causing [8] on Earth. A total lunar eclipse can also be called a blood moon. It makes the moon appear reddish-orange, similar to [9]. The color comes from small amounts of sunlight [10]. The American space agency NASA says lunar and solar eclipses happen [11]. The last total lunar eclipse was [12]. This one will be visible [13] starting Friday morning at [14] Eastern Daylight Time, or EDT. The time when the Earth’s shadow covers all of the moon will be close to 3 a.m. EDT. “[15], you should be able to see it,” Shannon Schmoll told the Associated Press. She is the director of Abrams Planetarium at Michigan State University. [16] will be needed to see the reddish moon. The total lunar eclipse may be harder to see in Europe and Africa because the moon will be [17]. Michael Faison is [18] from Yale University. He told the AP, “This is really an eclipse for North and South America.” Zoe Ortiz is a historian with the University of North Texas.",
      "She noted that [19] have observed lunar eclipses [20]. This helped [21] learn things about the behaviors of the sun, moon, and stars. “They were looking at the night sky and they had [22] than we do today,” Ortiz said. The ancient Greek thinker and writer Aristotle observed that Earth’s shadow on the moon during a lunar eclipse [23]. This fact [24]. The next total lunar eclipse will appear in the sky September 7, across parts of Asia, Africa, Australia and Europe.",
      "Parts of the Americas will get the next chance to see one [25]. I’m Caty Weaver."
    ],
    "answers": [
      "a reddish color",
      "Thursday night into Friday morning",
      "get brief views",
      "line up just right",
      "positioned between the sun and moon",
      "create a shadow",
      "blocks light from the sun",
      "a partial or full shadow",
      "the element copper",
      "passing through the Earth’s atmosphere",
      "between four and seven times a year",
      "in 2022",
      "for about one hour",
      "2:26 a.m.",
      "As long as the sky is clear",
      "No special equipment",
      "close to setting",
      "an astronomy expert",
      "different civilizations",
      "for thousands of years",
      "ancient people",
      "a much brighter vision",
      "was always curved",
      "supported proof that the Earth is round",
      "in March 2026"
    ],
    "acceptedVariants": [
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [
        "between 4 and 7 times a year"
      ],
      [
        "in twenty twenty-two",
        "in two thousand and twenty-two"
      ],
      [
        "for about 1 hour"
      ],
      [
        "2.26 am",
        "two twenty-six am",
        "two twenty six a.m."
      ],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [
        "in March twenty twenty-six",
        "in March two thousand and twenty-six"
      ]
    ],
    "contentRevision": "5a878733f944",
    "paraphrases": [
      [
        "get brief views",
        "see it for a short time",
        "Brief nói về thời gian quan sát ngắn, không phải hình ảnh mờ.",
        25.8,
        33.2
      ],
      [
        "line up just right",
        "be in exactly the right alignment",
        "Các thiên thể nằm đúng vị trí thẳng hàng cần thiết.",
        34.4,
        47.4
      ],
      [
        "blocks light from the sun",
        "prevents sunlight from passing through",
        "Block được diễn giải bằng prevent; giữ đúng đối tượng là ánh sáng.",
        67.2,
        79.7
      ],
      [
        "passing through the Earth’s atmosphere",
        "travelling through the layer of gases around Earth",
        "Atmosphere là lớp khí bao quanh Trái Đất.",
        94.8,
        101.8
      ],
      [
        "will be visible",
        "will be possible to see",
        "Visible nói về khả năng nhìn thấy.",
        122,
        135.3
      ],
      [
        "As long as the sky is clear",
        "Provided that there are no clouds in the sky",
        "As long as ở đây diễn đạt điều kiện, không phải độ dài thời gian.",
        145.5,
        154.7
      ],
      [
        "No special equipment will be needed",
        "You will not need any specialised devices",
        "Đổi câu bị động sang chủ động và giữ nguyên ý phủ định.",
        163.7,
        169.1
      ],
      [
        "the moon will be close to setting",
        "the moon will soon disappear below the horizon",
        "Setting nói về thiên thể lặn xuống dưới đường chân trời.",
        171,
        180.8
      ],
      [
        "for thousands of years",
        "over a period of several millennia",
        "Một millennium bằng một nghìn năm.",
        204.4,
        213.2
      ],
      [
        "supported proof that the Earth is round",
        "provided evidence of Earth's round shape",
        "Bằng chứng hình dạng bóng Trái Đất hỗ trợ nhận định Trái Đất tròn.",
        234.1,
        252.1
      ]
    ],
    "vocabulary": [
      {
        "term": "lunar eclipse",
        "meaning": "nguyệt thực",
        "note": "An event in which Earth's shadow falls on the moon."
      },
      {
        "term": "hemisphere",
        "meaning": "bán cầu",
        "note": "One half of the Earth."
      },
      {
        "term": "line up",
        "meaning": "nằm thẳng hàng",
        "note": "To form a straight line."
      },
      {
        "term": "solar eclipse",
        "meaning": "nhật thực",
        "note": "An event in which the moon blocks the sun from view."
      },
      {
        "term": "partial",
        "meaning": "một phần; không hoàn toàn",
        "note": "Covering only part of something."
      },
      {
        "term": "copper",
        "meaning": "đồng",
        "note": "A reddish-brown metal."
      },
      {
        "term": "atmosphere",
        "meaning": "khí quyển",
        "note": "The gases surrounding a planet."
      },
      {
        "term": "visible",
        "meaning": "có thể nhìn thấy",
        "note": "Able to be seen."
      },
      {
        "term": "civilization",
        "meaning": "nền văn minh",
        "note": "An organised human society with its own culture."
      },
      {
        "term": "curved",
        "meaning": "cong",
        "note": "Bent rather than straight."
      }
    ],
    "signals": [
      "Another kind of eclipse…",
      "As long as…",
      "This fact supported…"
    ]
  },
  "2": {
    "paragraphs": [
      "A recent study suggests the next ice age will likely begin [1] unless emissions change the effects of [2]. An ice age is [3] causing ice to cover large areas of the northern and southern parts of the world. A group of scientists studied changes in the shape of the Earth’s orbit around the sun, [4] and the movement of the axis itself, called a wobble. These three motions are believed to [5]. The Serbian scientist Milutin Milankovitch [6] about 100 years ago that these cycles affected [7]. The team noted that small changes in Earth’s orbit around the Sun caused [8] over a period of [9].",
      "These findings permitted the team to determine how the three factors of tilt, wobble, and the shape of Earth's orbit might have affected the Earth’s climate [10]. The group published its findings in Science on February 27. The scientists examined [11] by looking at ice sheets across the northern half of the world and [12]. They then compared this data with [13] in Earth’s orbit over time. The lead writer of this study is Stephen Barker, a professor at Cardiff University in Britain. He told the French News Agency AFP that for many years it has been difficult for scientists to show exactly how small changes in Earth’s orbit [14] between warm and cold periods.",
      "Earth is believed to [15] of ice ages and warm periods. The last ice age is thought to have ended [16]. Scientists, such as Milankovitch, have long seen [17]. However, researchers have struggled to [18] when each of the climate changes happened. It has also been difficult for them to know exactly which orbit positions affect [19] of cold or warm periods.",
      "Barker said his team of researchers studied [20] [21] instead of only looking at shorter periods of change between cold and warm climates. Barker told AFP, \"We would expect a glaciation to occur [22], and it would end in [23].\" Lorraine Lisiecki is a professor at the University of California, Santa Barbara, and a co-writer of the study. She said the study shows that changes in climate over tens of thousands of years [24]. The team aims to expand its findings to investigate [25] on climate. They also want to find out how it might affect Earth’s natural climate cycles. I’m Andrew Smith."
    ],
    "answers": [
      "in about 11,000 years",
      "natural climate cycles",
      "a period of reduced temperatures",
      "the tilt of the Earth’s axis",
      "happen in cycles",
      "developed a theory",
      "Earth’s long-term climate",
      "predictable cycles of warming and cooling",
      "about 100,000 years",
      "over the last 900,000 years",
      "a million-year record of climate",
      "deep ocean temperatures",
      "small but regular changes",
      "have led to huge changes",
      "go through cycles",
      "around 11,700 years ago",
      "a connection between Earth's orbit and climate",
      "precisely date",
      "the start and stop",
      "slow changes in temperature",
      "over long periods of time",
      "within the next 11,000 years",
      "66,000 years' time",
      "are not random",
      "the long-term effects of human activity"
    ],
    "acceptedVariants": [
      [
        "in about eleven thousand years"
      ],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [
        "about a hundred thousand years",
        "about one hundred thousand years"
      ],
      [
        "over the last nine hundred thousand years"
      ],
      [
        "a million year record of climate"
      ],
      [],
      [],
      [],
      [],
      [
        "around eleven thousand seven hundred years ago"
      ],
      [],
      [],
      [],
      [],
      [],
      [
        "within the next eleven thousand years"
      ],
      [
        "sixty-six thousand years' time",
        "sixty six thousand years time"
      ],
      [],
      []
    ],
    "contentRevision": "a00162e0328d",
    "paraphrases": [
      [
        "will likely begin",
        "will probably start",
        "Giữ nguyên mức độ dự đoán của likely.",
        0.7,
        13.1
      ],
      [
        "a period of reduced temperatures",
        "a time when temperatures are lower",
        "Reduced temperatures chỉ nhiệt độ thấp hơn.",
        14.6,
        24.8
      ],
      [
        "happen in cycles",
        "recur in a repeating pattern",
        "Cycle diễn tả một chuỗi có tính lặp lại.",
        41.6,
        46.2
      ],
      [
        "permitted the team to determine",
        "enabled the researchers to establish",
        "Permit ở đây là tạo điều kiện để tìm ra, không phải cấp giấy phép.",
        76.6,
        94.3
      ],
      [
        "a million-year record of climate",
        "climate evidence covering one million years",
        "Giữ nguyên độ dài hồ sơ khí hậu là một triệu năm.",
        102.5,
        115.1
      ],
      [
        "have led to huge changes",
        "have brought about major shifts",
        "Lead to và bring about cùng chỉ quan hệ nguyên nhân–kết quả.",
        134.2,
        152.9
      ],
      [
        "precisely date",
        "identify exactly when something occurred",
        "Date là động từ xác định niên đại, không phải hẹn hò.",
        178.2,
        185.7
      ],
      [
        "instead of only looking at shorter periods",
        "rather than examining just briefer intervals",
        "Giữ nguyên sự đối chiếu giữa khoảng dài và khoảng ngắn.",
        198.6,
        214.5
      ],
      [
        "are not random",
        "do not happen purely by chance",
        "Not random nói rằng có quy luật, không hoàn toàn ngẫu nhiên.",
        240.1,
        248.5
      ],
      [
        "investigate the long-term effects of human activity",
        "study how human actions influence climate over extended periods",
        "Investigate là nghiên cứu; giữ nguyên đối tượng và thời gian dài hạn.",
        250,
        266.4
      ]
    ],
    "vocabulary": [
      {
        "term": "ice age",
        "meaning": "kỷ băng hà",
        "note": "A long period when large areas of Earth are covered by ice."
      },
      {
        "term": "emission",
        "meaning": "sự phát thải; chất phát thải",
        "note": "The release of gases or other substances."
      },
      {
        "term": "orbit",
        "meaning": "quỹ đạo",
        "note": "The path of one object around another in space."
      },
      {
        "term": "tilt",
        "meaning": "độ nghiêng; sự nghiêng",
        "note": "A sloping position away from the vertical."
      },
      {
        "term": "axis",
        "meaning": "trục",
        "note": "An imaginary line around which an object rotates."
      },
      {
        "term": "wobble",
        "meaning": "sự lắc; dao động",
        "note": "An unsteady movement from side to side."
      },
      {
        "term": "predictable",
        "meaning": "có thể dự đoán",
        "note": "Possible to anticipate because a pattern is known."
      },
      {
        "term": "glaciation",
        "meaning": "quá trình băng hà hóa",
        "note": "The formation and spread of large ice sheets."
      },
      {
        "term": "random",
        "meaning": "ngẫu nhiên",
        "note": "Without a clear pattern or predictable order."
      },
      {
        "term": "investigate",
        "meaning": "nghiên cứu; điều tra",
        "note": "To examine something carefully to find out more."
      }
    ],
    "signals": [
      "These findings permitted…",
      "They then compared…",
      "However, researchers…",
      "instead of…"
    ]
  },
  "3": {
    "paragraphs": [
      "Many years have passed since the first spacecraft landed on the moon in 1966. From then until now, there have been [1] with [2]. Here is a short history of some of these attempts. The Soviet Union’s Luna 9 spacecraft was the first to land on the moon. It [3] in 1966. The landing came after several other Soviet spacecraft either did not reach the moon or crashed on the surface. The American space agency NASA says Luna 9 was the first spacecraft to [4] on the moon. It was also the first to send \"[5]\" from the moon’s surface to Earth. Luna 9’s landing proved \"the lunar surface could [6] and that an object would not sink into [7] as some models predicted,\" NASA said.",
      "In May 1966, the United States followed with its Surveyor 1 mission. NASA describes this effort as \"the first of [8] sent to the moon to [9] for NASA's Apollo missions.\" The successful soft landing of Surveyor 1 \"was one of the great successes of NASA's [10].\" Both the U.S. and Soviet Union had other successful robotic landings. Next, the countries aimed to [11] on the moon.",
      "In 1969, NASA successfully landed Apollo 11 astronauts Neil Armstrong and Buzz Aldrin on the moon. The U.S. Apollo program sent [12] to explore the moon [13]. Apollo 17 was the last in 1972. The U.S. is still the only country to land humans on the moon. NASA officials say the agency’s Artemis program aims to return astronauts to the lunar surface possibly [14]. In 2013, China became the third country to successfully land a spacecraft on the moon. China landed [15], or rover named Yutu that year. China followed with the Yutu-2 rover in 2019, this time touching down on [16]. In 2020, China successfully returned samples of rock and dirt collected by the rovers. The mission returned about [17] collected from the near side of the moon.",
      "Then in 2024, another mission returned [18] from the less explored far side of the moon. China has said it aims to land its astronauts on the moon [19]. In 2023, Russia tried its first moon landing [20]. The Luna 25 spacecraft was attempting to land [21]. But it is believed to have crash landed on the moon’s surface. The country’s last effort before that, Luna 24 in 1976, landed successfully and [22].",
      "After its first lander crashed into the moon in 2019, India made [23] in 2023. The country successfully landed its Chandrayaan-3 spacecraft on the lunar surface. The mission made India the fourth nation to complete a moon landing. In January 2024, Japan became the fifth country to successfully land a spacecraft on the moon. But the SLIM spacecraft [24]. This caused some [25], but the lander was able to operate for a short time. I’m Bryan Lynn."
    ],
    "answers": [
      "many additional attempts",
      "some succeeding and others failing",
      "touched down on the lunar surface",
      "carry out a soft landing",
      "photographic data",
      "support the weight of a lander",
      "a loose layer of dust",
      "a series of seven robotic spacecraft",
      "gather data in preparation",
      "early lunar and interplanetary program",
      "be the first to land humans",
      "12 astronauts",
      "over six missions",
      "by the end of 2026",
      "an exploring vehicle",
      "the moon’s unexplored far side",
      "1.7 kilograms of lunar material",
      "rock and soil samples",
      "by 2030",
      "in nearly 50 years",
      "near the lunar south pole",
      "returned moon rocks to Earth",
      "its second attempt",
      "landed upside down",
      "power and communication problems"
    ],
    "acceptedVariants": [
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [
        "a series of 7 robotic spacecraft"
      ],
      [],
      [
        "early lunar and interplanetary programme"
      ],
      [],
      [
        "twelve astronauts"
      ],
      [
        "over 6 missions"
      ],
      [
        "by the end of twenty twenty-six",
        "by the end of two thousand and twenty-six"
      ],
      [],
      [],
      [
        "one point seven kilograms of lunar material",
        "1.7 kilogrammes of lunar material",
        "1.7 kg of lunar material"
      ],
      [],
      [
        "by twenty thirty",
        "by two thousand and thirty"
      ],
      [
        "in nearly fifty years"
      ],
      [],
      [],
      [],
      [],
      []
    ],
    "contentRevision": "507c5ee8e48e",
    "paraphrases": [
      [
        "many additional attempts",
        "numerous further efforts",
        "Additional và further đều chỉ những lần thử tiếp theo.",
        9.8,
        19.3
      ],
      [
        "touched down on the lunar surface",
        "landed on the surface of the moon",
        "Touch down là hạ cánh; lunar nghĩa là thuộc Mặt Trăng.",
        33,
        37.3
      ],
      [
        "carry out a soft landing",
        "make a controlled landing without crashing",
        "Soft landing chỉ hạ cánh có kiểm soát thay vì đâm xuống bề mặt.",
        48.1,
        60.1
      ],
      [
        "support the weight of a lander",
        "hold a landing craft without it sinking",
        "Support the weight được giải thích theo ngữ cảnh sức chịu tải của bề mặt.",
        69.5,
        87
      ],
      [
        "gather data in preparation for",
        "collect information to get ready for",
        "Gather là thu thập; in preparation for diễn đạt mục đích chuẩn bị.",
        96.1,
        110.1
      ],
      [
        "aimed to be the first",
        "sought to achieve something before anyone else",
        "Aim to và seek to cùng diễn đạt mục tiêu, chưa khẳng định đã đạt được.",
        130.5,
        136.8
      ],
      [
        "possibly by the end of 2026",
        "perhaps no later than the close of 2026",
        "Giữ nguyên sự chưa chắc chắn của possibly và hạn thời gian by.",
        169.6,
        182
      ],
      [
        "the moon’s unexplored far side",
        "the previously unexamined side facing away from Earth",
        "Far side là phía quay xa Trái Đất; unexplored chỉ chưa được khảo sát trong ngữ cảnh câu.",
        199.1,
        209.5
      ],
      [
        "landed upside down",
        "came to rest with its top facing downwards",
        "Upside down nghĩa là lộn ngược, không chỉ nghiêng sang bên.",
        314.6,
        319
      ],
      [
        "was able to operate for a short time",
        "managed to function briefly",
        "Operate và function đều chỉ hoạt động của thiết bị.",
        319.7,
        328.9
      ]
    ],
    "vocabulary": [
      {
        "term": "spacecraft",
        "meaning": "tàu vũ trụ",
        "note": "A vehicle designed to travel in space."
      },
      {
        "term": "touch down",
        "meaning": "hạ cánh; tiếp đất",
        "note": "To reach the ground after flying."
      },
      {
        "term": "lunar",
        "meaning": "thuộc Mặt Trăng",
        "note": "Relating to the moon."
      },
      {
        "term": "lander",
        "meaning": "thiết bị đổ bộ",
        "note": "A spacecraft designed to land on a surface."
      },
      {
        "term": "robotic",
        "meaning": "thuộc robot; tự động",
        "note": "Controlled by machines rather than people on board."
      },
      {
        "term": "in preparation for",
        "meaning": "để chuẩn bị cho",
        "note": "As part of getting ready for an event or task."
      },
      {
        "term": "interplanetary",
        "meaning": "liên hành tinh",
        "note": "Between planets."
      },
      {
        "term": "rover",
        "meaning": "xe tự hành thăm dò",
        "note": "A vehicle that moves across a planet or moon to explore it."
      },
      {
        "term": "sample",
        "meaning": "mẫu vật",
        "note": "A small amount collected for examination."
      },
      {
        "term": "upside down",
        "meaning": "lộn ngược",
        "note": "With the top part at the bottom."
      }
    ],
    "signals": [
      "From then until now…",
      "It was also the first…",
      "Next, the countries…",
      "But it is believed…"
    ]
  },
  "4": {
    "paragraphs": [
      "A new study suggests [1] are [2]. The research identifies a protein – found only in people – that may have helped early humans [3]. Scientists involved in the study say this new speaking ability became [4]. For example, speech permitted individuals to share information, organize activities and [5]. These abilities are now seen as [6] humans had over their relatives, such as the Neanderthals and Denisovans. The researchers recently [7] in a study in the journal Nature Communications.",
      "Liza Finestack teaches about speech and hearing at the University of Minnesota. She told The Associated Press, or AP, the new study is \"a good first step to start looking at [8]\" that may affect [9]. Finestack was [10]. Dr. Robert Darnell has long been studying the protein – called NOVA1 – at his laboratory at New York’s Rockefeller University. He helped lead the new research and was a writer of the study. Darnell told the AP the genetic version, or variant, included the protein that helped humans develop into the “[11]” that remains today. The latest research involved scientists using CRISPR [12] to replace the NOVA1 protein found in mice with the one found in humans.",
      "The aim was to test [13]. The researchers were surprised to learn that the variant changed the way the animals [14]. Baby mice with the human variant [15] than normal mice do when their mother came around. Adult male mice with the variant also made different sounds when they were near a female they wanted to mate with. Darnell said both of these situations gave the mice [16]. Those with the human variant \"spoke differently,\" demonstrating [17], he added. This is not the first time a gene has been linked to speech. [18], British scientists said they had discovered the first gene tied to [19].",
      "Researchers called this human language gene FOXP2. But even though FOXP2 was found to be linked to human language, the variant in modern humans was not found in [20]. Later research found it was shared with Neanderthals. The NOVA1 variant in modern humans, [21], is found only in our species, Darnell said. The presence of a gene variant is [22] that permits people to speak. The ability also depends on [23] and areas of the brain that work together to help people produce speech and understand language. Darnell said he hopes the recent work can lead to new ways to treat [24].",
      "The University of Minnesota's Finestack noted the genetic findings could also one day permit scientists to identify people who might need help developing speech and language [25]. \"That's certainly a possibility,\" she said. I’m Jill Robbins."
    ],
    "answers": [
      "the beginnings of human speech",
      "linked to genetics",
      "develop spoken communication",
      "important for humans’ survival",
      "pass down knowledge",
      "an advantage",
      "published their findings",
      "the specific genes",
      "speech and language development",
      "not involved in the study",
      "dominant species",
      "gene editing methods",
      "the real-life effects of the genetic variant",
      "called out to each other",
      "made a different sound",
      "a reason to speak",
      "the gene’s influence in speech",
      "In 2001",
      "a language and speech disorder",
      "our species alone",
      "on the other hand",
      "not the only thing",
      "physical elements in the human throat",
      "speech-related problems",
      "early in life"
    ],
    "acceptedVariants": [
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [
        "in two thousand and one",
        "in two thousand one",
        "in twenty oh one"
      ],
      [],
      [],
      [],
      [],
      [],
      [],
      []
    ],
    "contentRevision": "c2752c1679be",
    "paraphrases": [
      [
        "are linked to genetics",
        "are connected with inherited biological characteristics",
        "Giữ nguyên quan hệ liên quan, không khẳng định một gen giải thích toàn bộ ngôn ngữ.",
        1.5,
        6.9
      ],
      [
        "pass down knowledge",
        "transmit what is known to later generations",
        "Pass down chỉ truyền lại qua thế hệ.",
        27.1,
        35.6
      ],
      [
        "may affect speech and language development",
        "could influence how speaking and language skills develop",
        "May và could đều giữ ý chưa chắc chắn.",
        62.2,
        74.5
      ],
      [
        "was not involved in the study",
        "did not take part in this research",
        "Giữ nguyên phủ định và quan hệ tham gia nghiên cứu.",
        75.6,
        78.3
      ],
      [
        "test the real-life effects",
        "examine the consequences in living subjects",
        "Ngữ cảnh là thử ảnh hưởng ở chuột sống, không chỉ trên lý thuyết.",
        120.4,
        124.8
      ],
      [
        "called out to each other",
        "made sounds to communicate with one another",
        "Diễn giải hành vi phát tiếng của chuột, không coi đó là lời nói của người.",
        126,
        132.7
      ],
      [
        "demonstrating the gene’s influence in speech",
        "showing that the gene affects vocal communication",
        "Demonstrating diễn đạt việc cho thấy ảnh hưởng của gen.",
        157.1,
        164.8
      ],
      [
        "was not found in our species alone",
        "was present in species other than humans too",
        "Not alone có nghĩa không chỉ riêng con người.",
        179.8,
        198.9
      ],
      [
        "on the other hand",
        "by contrast",
        "Cụm nối báo hiệu sự đối chiếu hai biến thể gen.",
        200.2,
        208.6
      ],
      [
        "can lead to new ways to treat speech-related problems",
        "may result in new treatments for speaking difficulties",
        "Giữ nguyên ý khả năng đóng góp cho phương pháp điều trị mới.",
        229.5,
        235.2
      ]
    ],
    "vocabulary": [
      {
        "term": "genetics",
        "meaning": "di truyền học",
        "note": "The study of genes and inherited characteristics."
      },
      {
        "term": "protein",
        "meaning": "protein; chất đạm",
        "note": "A complex molecule with important functions in living cells."
      },
      {
        "term": "survival",
        "meaning": "sự sống sót; sinh tồn",
        "note": "The state of continuing to live."
      },
      {
        "term": "pass down",
        "meaning": "truyền lại",
        "note": "To give knowledge or traditions to a later generation."
      },
      {
        "term": "dominant",
        "meaning": "chiếm ưu thế; có ảnh hưởng lớn nhất",
        "note": "Having the greatest influence or control."
      },
      {
        "term": "variant",
        "meaning": "biến thể",
        "note": "A form that differs from other forms of the same thing."
      },
      {
        "term": "gene editing",
        "meaning": "chỉnh sửa gen",
        "note": "Making targeted changes to genetic material."
      },
      {
        "term": "mate",
        "meaning": "giao phối",
        "note": "To breed in order to produce young."
      },
      {
        "term": "disorder",
        "meaning": "rối loạn",
        "note": "A condition that disrupts normal physical or mental functioning."
      },
      {
        "term": "identify",
        "meaning": "xác định; nhận diện",
        "note": "To recognise or establish who or what something is."
      }
    ],
    "signals": [
      "For example…",
      "The aim was…",
      "But even though…",
      "on the other hand…"
    ]
  },
  "5": {
    "paragraphs": [
      "A private spacecraft [1] has successfully landed on the moon. The lander, called Blue Ghost, was built by the American company Firefly Aerospace. The spacecraft touched down March 2 on the part of the moon’s near side called Mare Crisium. The near side of the moon is [2]. Officials at Firefly’s Mission Control center near Austin, Texas, [3]. The chief engineer for the Blue Ghost mission, Will Coogan, announced to excited workers: “We’re on the moon.” The officials said the spacecraft landed [4] and was [5]. The successful touchdown makes Firefly [6] to land a spacecraft on the moon [7]. Only five countries can claim successful moon landings: Russia, the United States, China, India and Japan. Blue Ghost is [8] found in the U.S. The four-legged lander is [9] and [10]. It launched in mid-January from Florida, carrying [11] for the American space agency NASA. In a statement, NASA said the 10 experiments are designed to operate on the surface of the moon for [12], which is [13]. The Associated Press reported that NASA paid [14] for the spacecraft and [15] for the equipment it carried.",
      "It was the third mission under NASA’s Commercial Lunar Payload Services (CLPS) program. The program aims to [16] the country’s major space missions to private companies to [17]. Several other companies are part of the program. Another lander, called Athena, is set to attempt a moon landing on March 6. That four-meter-tall spacecraft was built and operated by Houston-based Intuitive Machines. It will land on another part of the moon, [18] from the lunar south pole.",
      "A third lander from private Japanese company ispace will attempt a moon landing [19]. The lander, called Resilience, shared its rocket ride with Blue Ghost. But it [20] to the moon. The company is also attempting to land on the moon [21]. Its first lander crashed in 2023. NASA has said it aims to have [22] launch to the moon each year, realizing [23]. The space agency’s top science officer is Nicky Fox. She told the AP the latest launches “open up a whole new way for us to get more science to space and to the moon.\" In the past, NASA’s successful moon landings involving astronauts cost billions of dollars. But Firefly chief Jason Kim said the private companies now building and launching spacecraft have [24] and the spacecraft operate robotically. Kim said everything [25] with Blue Ghost’s landing. “We got some moon dust on our boots,\" he added. I’m Bryan Lynn."
    ],
    "answers": [
      "carrying several science experiments",
      "the side facing Earth",
      "confirmed the successful landing",
      "in the right position",
      "operating normally",
      "the first private company",
      "without crashing or having a major problem",
      "named after a rare kind of firefly",
      "two meters tall",
      "3.5 meters wide",
      "10 experiments",
      "one lunar day",
      "about 14 Earth days",
      "$101 million",
      "$44 million",
      "turn over",
      "reduce costs",
      "about 160 kilometers",
      "in about three months",
      "took a longer path",
      "for the second time",
      "two private landers",
      "some missions will fail",
      "a limited budget",
      "went just as planned"
    ],
    "acceptedVariants": [
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [
        "2 meters tall",
        "two metres tall",
        "2 metres tall"
      ],
      [
        "three point five meters wide",
        "3.5 metres wide",
        "three point five metres wide"
      ],
      [
        "ten experiments"
      ],
      [
        "1 lunar day"
      ],
      [
        "about fourteen Earth days"
      ],
      [
        "101 million dollars",
        "a hundred and one million dollars",
        "one hundred and one million dollars",
        "one hundred one million dollars"
      ],
      [
        "44 million dollars",
        "forty-four million dollars"
      ],
      [],
      [],
      [
        "about a hundred and sixty kilometers",
        "about one hundred and sixty kilometers",
        "about one hundred sixty kilometers",
        "about 160 kilometres"
      ],
      [
        "in about 3 months"
      ],
      [],
      [],
      [
        "2 private landers"
      ],
      [],
      [],
      []
    ],
    "contentRevision": "5592517ed9a4",
    "paraphrases": [
      [
        "the side facing Earth",
        "the half directed towards our planet",
        "Facing diễn tả hướng của một phía Mặt Trăng.",
        28.5,
        33.4
      ],
      [
        "was operating normally",
        "was functioning as expected",
        "Operate và function đều chỉ hoạt động của thiết bị.",
        52.7,
        63.6
      ],
      [
        "without crashing or having a major problem",
        "without an impact accident or serious difficulty",
        "Giữ nguyên cả hai điều kiện, không chỉ nói hạ cánh thành công.",
        63.6,
        78.2
      ],
      [
        "is named after a rare kind of firefly",
        "takes its name from an uncommon type of insect",
        "Named after chỉ nguồn gốc tên gọi; rare là hiếm.",
        85.1,
        98.2
      ],
      [
        "designed to operate on the surface of the moon",
        "intended to function on the lunar ground",
        "Designed to nói về mục đích thiết kế.",
        116.9,
        130.3
      ],
      [
        "to reduce costs",
        "to lower expenses",
        "Reduce costs và lower expenses cùng chỉ giảm chi phí.",
        153.8,
        169.6
      ],
      [
        "took a longer path to the moon",
        "travelled to the moon by a less direct route",
        "Longer path đối chiếu với chuyến đi của Blue Ghost.",
        204.7,
        222.9
      ],
      [
        "realizing some missions will fail",
        "recognising that not every mission will succeed",
        "Đổi fail thành phủ định của succeed và giữ some.",
        230.5,
        246.2
      ],
      [
        "have a limited budget",
        "have only a restricted amount of money available",
        "Budget là ngân sách, không phải số tiền đã chi hết.",
        267.9,
        284.6
      ],
      [
        "everything went just as planned",
        "the entire operation happened as intended",
        "Giữ ý mọi việc diễn ra đúng kế hoạch.",
        281,
        293
      ]
    ],
    "vocabulary": [
      {
        "term": "experiment",
        "meaning": "thí nghiệm",
        "note": "A scientific test carried out to learn something."
      },
      {
        "term": "mission control",
        "meaning": "trung tâm điều khiển nhiệm vụ",
        "note": "The team and facilities directing a space mission."
      },
      {
        "term": "touchdown",
        "meaning": "sự hạ cánh",
        "note": "The moment a vehicle reaches the ground."
      },
      {
        "term": "rare",
        "meaning": "hiếm",
        "note": "Not common or frequently found."
      },
      {
        "term": "launch",
        "meaning": "phóng; khởi động",
        "note": "To send a spacecraft on its journey."
      },
      {
        "term": "payload",
        "meaning": "tải trọng hữu ích",
        "note": "The equipment or cargo a vehicle carries for its mission."
      },
      {
        "term": "turn over",
        "meaning": "chuyển giao",
        "note": "To give control or responsibility to someone else."
      },
      {
        "term": "resilience",
        "meaning": "khả năng phục hồi; sức bền bỉ",
        "note": "The ability to recover after difficulty."
      },
      {
        "term": "budget",
        "meaning": "ngân sách",
        "note": "The amount of money available for a purpose."
      },
      {
        "term": "robotically",
        "meaning": "bằng robot; theo cơ chế tự động",
        "note": "Using machines rather than people on board."
      }
    ],
    "signals": [
      "In a statement…",
      "The program aims…",
      "But it took…",
      "In the past…"
    ]
  },
  "6": {
    "paragraphs": [
      "Scientists say they might have identified the mineral on Mars that is [1]. New data collected on Mars through several methods suggests the substance, called ferrihydrite, is likely found in [2] across wide areas of the planet. The team carrying out the research describes ferrihydrite as an “[3].” The mineral appears reddish in color and can form in [4]. The scientists said discovering large amounts of it on Mars [5] that the planet might have held [6] in the past. The research was carried out by [7] led by America’s Brown University and the University of Bern in Switzerland.",
      "The findings recently appeared in a study published in Nature Communications. The researchers noted that scientists have long wondered about [8] that gives Mars – which is also known as the Red Planet – [9]. Past studies had suggested a mineral called hematite [10]. The study is based on [11]. These include the Mars Reconnaissance Orbiter, operated by the American space agency NASA. In addition, information was captured by [12] the European Space Agency’s (ESA's) Mars Express and Trace Gas orbiters. Some data also came from [13], called rovers, operating on Mars.",
      "In their examinations, the researchers also used [14] designed to [15] to real Martian dust. Adomas Valantinas currently works as a researcher at Brown University’s Department of Earth, Environment and Planetary Sciences. He helped write the study. Valantinas noted the mystery of why Mars is red had been considered “[16].” Valantinas recognized his team was not the first to consider ferrihydrite [17] for the coloring of Mars. But he noted, “it has never been proven as we have now, using [18] and [19]…” Valantinas noted the discovery of widespread ferrihydrite suggests Mars once held liquid water that would have made it possible for the planet to [20].",
      "\"Our study reveals that ferrihydrite formation on Mars required [21] and water [22],” he added. “These conditions were very different from [23] of Mars today.\" John Mustard is a planetary expert at Brown University and was a co-writer of the study. He called it “a door-opening opportunity” for future research. But he added that [24] to confirm the team’s latest findings. \"As exciting as the new findings are, we realize that our results [25], which are currently being collected by NASA's Perseverance rover,” Mustard said.",
      "He added, “When we get those back, we will be able to check whether our theory about ferrihydrite is correct.\" I’m Bryan Lynn."
    ],
    "answers": [
      "responsible for making the planet appear red",
      "dust and rock material",
      "iron oxide mineral",
      "water-rich environments",
      "adds to existing evidence",
      "a large supply of liquid water",
      "an international team",
      "the exact substance",
      "its deep red color",
      "might be the cause",
      "Martian data collected by several spacecraft",
      "instruments aboard",
      "exploring vehicles",
      "manmade, or synthetic, material",
      "look and feel similar",
      "for hundreds, if not thousands, of years",
      "as a possible reason",
      "observational data",
      "novel laboratory methods",
      "support some form of life",
      "the presence of both oxygen",
      "capable of reacting with iron",
      "the dry, cold environment",
      "additional study is needed",
      "can only be verified by samples from Mars"
    ],
    "acceptedVariants": [
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [
        "its deep red colour"
      ],
      [],
      [],
      [],
      [],
      [
        "man-made or synthetic material"
      ],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      []
    ],
    "contentRevision": "522473a04798",
    "paraphrases": [
      [
        "might have identified",
        "may have discovered the identity of",
        "Giữ nguyên sự chưa chắc chắn của might; không đổi thành đã chứng minh.",
        0,
        13.3
      ],
      [
        "is likely found",
        "is probably present",
        "Likely và probably cùng thể hiện khả năng cao.",
        14.3,
        32
      ],
      [
        "water-rich environments",
        "surroundings containing plenty of water",
        "Diễn giải tính từ ghép water-rich.",
        42.8,
        50.8
      ],
      [
        "adds to existing evidence",
        "provides further support for what was already indicated",
        "Adds to bổ sung bằng chứng, không khẳng định chứng minh tuyệt đối.",
        51.4,
        67.8
      ],
      [
        "the research was carried out",
        "the investigation was conducted",
        "Carry out và conduct là hai cách nói thực hiện nghiên cứu.",
        69,
        81.3
      ],
      [
        "manmade, or synthetic, material",
        "a substance created artificially",
        "Synthetic và manmade chỉ vật liệu được con người tạo ra.",
        157.1,
        171
      ],
      [
        "novel laboratory methods",
        "new techniques used in laboratory experiments",
        "Novel ở đây nghĩa là mới, không phải tiểu thuyết.",
        212.8,
        224.5
      ],
      [
        "support some form of life",
        "sustain living organisms of some kind",
        "Support life là duy trì điều kiện cho sự sống.",
        225.8,
        242.1
      ],
      [
        "additional study is needed",
        "further investigation is required",
        "Giữ ý cần nghiên cứu thêm trước khi xác nhận.",
        283.7,
        291.7
      ],
      [
        "check whether our theory about ferrihydrite is correct",
        "test if our explanation involving this mineral is accurate",
        "Whether giữ nguyên câu hỏi về tính đúng sai của giả thuyết.",
        310.3,
        322.1
      ]
    ],
    "vocabulary": [
      {
        "term": "mineral",
        "meaning": "khoáng vật",
        "note": "A naturally occurring substance found in rocks."
      },
      {
        "term": "iron oxide",
        "meaning": "oxit sắt",
        "note": "A compound containing iron and oxygen."
      },
      {
        "term": "evidence",
        "meaning": "bằng chứng",
        "note": "Information that supports or challenges an explanation."
      },
      {
        "term": "liquid",
        "meaning": "ở thể lỏng; chất lỏng",
        "note": "A state of matter that flows and takes the shape of its container."
      },
      {
        "term": "orbiter",
        "meaning": "tàu quỹ đạo",
        "note": "A spacecraft travelling around a planet or moon."
      },
      {
        "term": "synthetic",
        "meaning": "nhân tạo; tổng hợp",
        "note": "Made artificially rather than occurring naturally."
      },
      {
        "term": "observational",
        "meaning": "thuộc quan sát",
        "note": "Based on watching or measuring what happens."
      },
      {
        "term": "novel",
        "meaning": "mới; mới lạ",
        "note": "New and different from earlier approaches."
      },
      {
        "term": "widespread",
        "meaning": "phân bố rộng; phổ biến",
        "note": "Present over a large area."
      },
      {
        "term": "verify",
        "meaning": "kiểm chứng; xác minh",
        "note": "To check whether something is true or accurate."
      }
    ],
    "signals": [
      "In addition…",
      "In their examinations…",
      "But he added…",
      "When we get those back…"
    ]
  },
  "7": {
    "paragraphs": [
      "Businessman Elon Musk said a third person has had [1] directly connected to their brain. [2] received an implant from Musk’s company Neuralink, which makes devices that link the human brain to computers. Neuralink is one of many groups working to connect [3] to machines. On the social media service X, which he owns, Musk said: \"We've got three humans with Neuralinks and all are working well.\" Neuralink announced [4] one year ago. Recently, Musk said the company has improved its devices. Musk also said Neuralink hopes to implant the experimental devices in [5] this year. The second patient reportedly has [6] and got the implant last summer. The person was playing video games [7] and learning how to use [8]. The first patient, also paralyzed after a spinal cord injury, said it helped him play video games and chess. Many other companies and research groups are working on [9]. Two studies published last year in the New England Journal of Medicine describe how [10], known as BCIs, helped people with Amyotrophic lateral sclerosis, or ALS, [11].",
      "ALS is a nervous system disease that affects cells in the brain and spinal cord. Nature magazine reported last September that there were published results from [12] of BCIs over [13]. Rajesh Rao is co-director of the Center for Neurotechnology at the University of Washington. Rao said that many [14] have already shown that humans can [15] using BCIs. Rao said Neuralink might be different from the others in two ways. First, the surgery to implant the device is the first to use a robot to implant [16] into a human brain to [17] and to control devices. Second, those connectors might record from [18] than interfaces from other research efforts.",
      "Rao said other companies such as Synchron, Blackrock Neurotech and Onward Medical are carrying out BCI tests on people using methods that are different from Neuralink. Marco Baptista is chief scientific officer of the Christopher and Dana Reeve Foundation. He called BCI technology \"very exciting\" with [19] to people with paralysis. Through clinical tests, \"we'll be able to see what's going to be [20],\" he said. \"It's a little early to know.\" A clinical trial follows [21] on how to design an experiment involving [22]. Neuralink announced in 2023 that it had [23] from U.S. officials to begin testing its device in people. The Food and Drug Administration, or FDA, is responsible for [24].",
      "Dr. Rita Redberg studies high-risk devices at the University of California, San Francisco. Redberg said that most medical devices go on the market without clinical trials. However, high-risk devices that are seeking approval from the FDA before they go on the market need what is called an \"[25].\" Neuralink says it has this exemption. I’m Jill Robbins."
    ],
    "answers": [
      "a special electronic device",
      "The unidentified person",
      "the human nervous system",
      "its first brain implant",
      "20 to 30 more people",
      "a spinal cord injury",
      "with the help of the device",
      "design software",
      "similar projects",
      "brain-computer interfaces",
      "communicate better",
      "28 trials worldwide",
      "the past 25 years",
      "research laboratories",
      "control computer cursors",
      "flexible electrical connectors",
      "record brain signals",
      "more parts of the brain",
      "possible benefits",
      "the winning approach",
      "established rules",
      "human subjects",
      "received permission",
      "approving the sale of medical devices",
      "investigational device exemption"
    ],
    "acceptedVariants": [
      [],
      [],
      [],
      [],
      [
        "twenty to thirty more people",
        "20-30 more people"
      ],
      [],
      [],
      [],
      [],
      [],
      [],
      [
        "twenty-eight trials worldwide"
      ],
      [
        "the past twenty-five years"
      ],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      []
    ],
    "contentRevision": "6aa16a83aa27",
    "paraphrases": [
      [
        "The unidentified person",
        "The individual whose identity was not disclosed",
        "Unidentified nói rằng bài báo không nêu danh tính người đó.",
        12.4,
        23.3
      ],
      [
        "has improved its devices",
        "has made its equipment better",
        "Giữ nguyên ý cải tiến thiết bị, không tự thêm kết luận về hiệu quả điều trị.",
        48.4,
        52.5
      ],
      [
        "hopes to implant the experimental devices",
        "aims to insert devices that are still being tested",
        "Hopes to diễn đạt kế hoạch; experimental chưa phải đã được xác nhận an toàn hoặc hiệu quả.",
        53.9,
        62.4
      ],
      [
        "with the help of the device",
        "with assistance from the equipment",
        "Diễn đạt cùng quan hệ được thiết bị hỗ trợ.",
        72,
        79.2
      ],
      [
        "are working on similar projects",
        "are developing comparable research initiatives",
        "Similar là tương tự, không có nghĩa hoàn toàn giống nhau.",
        90.3,
        95.3
      ],
      [
        "published results from 28 trials worldwide",
        "released findings from twenty-eight tests around the world",
        "Giữ nguyên số lượng 28 và phạm vi toàn cầu.",
        123.4,
        134.3
      ],
      [
        "might be different from the others in two ways",
        "may differ from the other systems in two respects",
        "Giữ tính dự đoán của might và số điểm khác biệt.",
        154,
        157.7
      ],
      [
        "possible benefits to people with paralysis",
        "potential advantages for people unable to move affected body parts",
        "Possible không đồng nghĩa chắc chắn có lợi; paralysis là liệt.",
        206.5,
        212.8
      ],
      [
        "follows established rules",
        "complies with procedures already set out",
        "Established rules là quy trình đã được đặt ra.",
        222.8,
        231.4
      ],
      [
        "are seeking approval",
        "are trying to obtain official permission",
        "Seeking approval chưa có nghĩa đã được phê duyệt.",
        265.8,
        277.2
      ]
    ],
    "vocabulary": [
      {
        "term": "implant",
        "meaning": "thiết bị cấy ghép; cấy ghép",
        "note": "A device placed inside the body, or the act of placing it there."
      },
      {
        "term": "nervous system",
        "meaning": "hệ thần kinh",
        "note": "The brain, spinal cord and nerves that carry signals through the body."
      },
      {
        "term": "spinal cord",
        "meaning": "tủy sống",
        "note": "The bundle of nerve tissue running through the spine."
      },
      {
        "term": "paralysis",
        "meaning": "tình trạng liệt",
        "note": "Loss of the ability to move part or all of the body."
      },
      {
        "term": "interface",
        "meaning": "giao diện; bộ phận kết nối",
        "note": "A connection through which two systems communicate."
      },
      {
        "term": "cursor",
        "meaning": "con trỏ",
        "note": "The movable marker showing a position on a computer screen."
      },
      {
        "term": "flexible",
        "meaning": "linh hoạt; có thể uốn cong",
        "note": "Able to bend without breaking."
      },
      {
        "term": "clinical trial",
        "meaning": "thử nghiệm lâm sàng",
        "note": "A planned research study involving human participants."
      },
      {
        "term": "approval",
        "meaning": "sự phê duyệt",
        "note": "Official permission for an action or product."
      },
      {
        "term": "exemption",
        "meaning": "sự miễn trừ",
        "note": "Permission not to follow a requirement that would otherwise apply."
      }
    ],
    "signals": [
      "First, the surgery…",
      "Second, those connectors…",
      "Through clinical tests…",
      "However, high-risk devices…"
    ]
  }
};
